---
- name: Enroll client certificate
  command: >
    step ca certificate
    "{{ item.common_name }}"
    "{{ item.cert_path }}"
    "{{ item.key_path }}"
    --provisioner "{{ item.provisioner }}"
    --provisioner-password-file "{{ item.provisioner_password_file }}"
  register: stepca_client_cert_output
  loop: "{{ stepca_client_enrollments }}"
  loop_control:
    label: "{{ item.common_name }}"
  notify: Log issued Step-CA client certificates
