# tasks/install_keycloak.yml
---
- name: Create Keycloak data directory
  file:
    path: "{{ keycloak_data_dir }}"
    state: directory
    owner: "{{ svc_keycloak }}"
    group: "{{ svc_keycloak }}"
    mode: '0755'

- name: Render Keycloak podman-compose.yml
  template:
    src: keycloak/podman-compose.yml.j2
    dest: "{{ keycloak_data_dir }}/podman-compose.yml"
    owner: "{{ svc_keycloak }}"
    group: "{{ svc_keycloak }}"
    mode: '0644'

- name: Render Keycloak systemd unit file
  template:
    src: keycloak/keycloak.service.j2
    dest: "/etc/systemd/system/keycloak.service"
  notify: Reload systemd and start keycloak
