---
- name: Pull Wazuh container image
  containers.podman.podman_image:
    name: wazuh/wazuh:latest

- name: Create Wazuh configuration directory
  file:
    path: "/opt/wazuh/config"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Wazuh container
  containers.podman.podman_container:
    name: wazuh-manager
    image: wazuh/wazuh:latest
    state: started
    restart_policy: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - "/opt/wazuh/config:/var/ossec/config:z"

- name: Ensure auditd is installed
  apt:
    name: auditd
    state: present
    update_cache: true
  become: true

- name: Ensure auditd service is enabled and started
  service:
    name: auditd
    state: started
    enabled: true
