---
- name: Deploy mailcow container with Podman
  containers.podman.podman_container:
    name: mailcow
    image: "{{ mailcow_image }}"
    state: started
    restart_policy: always
    volumes:
      - "{{ mailcow_data_dir }}:/data:z"
    env:
      CONFIG_PATH: "/data/config"

- name: Ensure systemd service is enabled for mailcow
  copy:
    dest: "/etc/systemd/system/podman-mailcow.service"
    content: |
      [Unit]
      Description=Podman container for mailcow
      Wants=network.target
      After=network.target

      [Service]
      ExecStart=/usr/bin/podman start -a mailcow
      ExecStop=/usr/bin/podman stop -t 10 mailcow
      Restart=always

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: "0644"

- name: Reload systemd and enable service for mailcow
  systemd:
    daemon_reload: yes
    name: podman-mailcow.service
    enabled: yes
    state: started
