---
- name: Ensure mailcow service directory exists
  file:
    path: "{{ service.compose_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ service.user | default('root') }}"
    group: "{{ service.group | default('root') }}"

- name: Deploy mailcow .env file from template
  template:
    src: mailcow/env.j2
    dest: "{{ service.compose_dir }}/.env"
    owner: "{{ service.user | default('root') }}"
    group: "{{ service.group | default('root') }}"
    mode: "0600"

- name: Copy mailcow podman-compose.yml
  copy:
    src: mailcow/podman-compose.yml
    dest: "{{ service.compose_dir }}/podman-compose.yml"
    owner: "{{ service.user | default('root') }}"
    group: "{{ service.group | default('root') }}"
    mode: "0644"

- name: Copy mailcow systemd unit file
  template:
    src: mailcow/mailcow.service.j2
    dest: /etc/systemd/system/podman-mailcow.service
    mode: "0644"

- name: Reload systemd daemon
  command: systemctl daemon-reexec

- name: Enable and start mailcow container service
  systemd:
    name: podman-mailcow.service
    enabled: true
    state: started
