---
- name: Ensure Podman and dependencies are installed
  apt:
    name:
      - podman
      - uidmap
      - slirp4netns
      - fuse-overlayfs
    state: present
  become: true

- name: Confirm Podman version
  command: podman --version
  register: podman_version
  changed_when: false

- name: Debug Podman version for audit
  debug:
    msg: "Podman version is {{ podman_version.stdout }}"

- name: Iterate over defined Podman services
  include_tasks: run_service.yml
  loop: "{{ podman_services }}"
  loop_control:
    loop_var: service
