# tasks/configure_realm.yml
---
- name: Wait for Keycloak to be ready
  uri:
    url: "http://localhost:{{ keycloak_port }}/realms/master"
    method: GET
    status_code: 200
  register: keycloak_status
  until: keycloak_status.status == 200
  retries: 10
  delay: 10

- name: Configure Keycloak realm and groups
  command: >
    /opt/keycloak/bin/kcadm.sh create realms -s realm={{ keycloak_realm }}
    -s enabled=true --server http://localhost:{{ keycloak_port }} --realm master
    --user {{ keycloak_admin_user }} --password {{ keycloak_admin_password }}
  args:
    creates: "/opt/keycloak/realms/{{ keycloak_realm }}.configured"
