# tasks/integrate_sso.yml
---
- name: Register Nextcloud client in Keycloak
  command: >
    /opt/keycloak/bin/kcadm.sh create clients -r {{ keycloak_realm }}
    -s clientId=nextcloud -s enabled=true
    -s protocol=saml
    --server http://localhost:{{ keycloak_port }}
    --realm master
    --user {{ keycloak_admin_user }} --password {{ keycloak_admin_password }}
  when: sso_nextcloud is defined
